In [2]:
import numpy as np

#we need two arrays for performing mathmatical operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1)
print(arr2)


[1 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
# addition 
#In list we have to first create loops then do further things to perform opeartions
#But in numpy its just very simple
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [ ]:
# Substraction
arr1-arr2

array([-5, -5, -5, -5, -5])

In [ ]:
# Multiplication
arr1*arr2


array([ 6, 14, 24, 36, 50])

In [ ]:
# Division
arr1/arr2


array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
# Floor division
arr1//arr2

array([0, 0, 0, 0, 0])

In [ ]:
# Exponentional
arr1**arr2

array([      1,     128,    6561,  262144, 9765625])