In [ ]:
# Broadcasting ka matlab hai NumPy chhoti shape wali array ko logically expand karke badi array ke saath element-wise operation kar deta hai, bina tumhe manually copy karne ki zarurat pade.
import numpy as np

arr1 = np.array([10,20,30,40,50])

arr1+10 #we can add small values directly to other instead of creating [10,10,10,10,10]

array([20, 30, 40, 50, 60])

In [3]:
arr2=np.arange(1,26).reshape(5,5)
print (arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [4]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [5]:
arr3=np.array([10,20,30,40,50])
arr2+arr3

array([[11, 22, 33, 44, 55],
       [16, 27, 38, 49, 60],
       [21, 32, 43, 54, 65],
       [26, 37, 48, 59, 70],
       [31, 42, 53, 64, 75]])

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20])

arr + b 
# will give error because size is not compatible