In [1]:
import numpy as np

arr1 = np.arange(1,21)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
slice = arr1[3:8] 
slice =slice *10
print(slice)

print(arr1)


# HERE YOU WILL SEE THAT THE OPERATION I PERFORMED ON SLICED PART OF ARR1 DOES NOT CHANGE ITS VALUE IN ORIGINAL ARR1
#because we are creating nedw array slic1 and then doing slice *10 if we directly do slice*10 then array will also change

[40 50 60 70 80]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
arr1
b = arr1
b[0] = 99
print(b)
print(arr1)

# now it gets changed because we are just copying same array so its get saved at same memory location so values called changed .


[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# to prevent above now value of b will just change
arr1
b = arr1.copy()
b[6] = 99
print(b)
print(arr1)


[99  2  3  4  5  6 99  8  9 10 11 12 13 14 15 16 17 18 19 20]
[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# Shallow copy mein outer object ki new copy banti hai, but andar ke nested objects original ke saath share hote hain.
# ➡️ Isliye nested data change karne par original bhi change ho sakta hai.

# Deep Copy
# B = copy.deepcopy(A)
# Deep copy mein outer object ke saath-saath andar ke nested objects ki bhi new copies banti hain.
# ➡️ Isliye copy mein change karne par original change nahi hota.

# Yaad rakhne ki trick:

# Shallow → andar share
# Deep → sab separate