In [7]:
import numpy as np

a = np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b) 

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
# multiplication of matrix

a @ b

#OR 

np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [11]:
# Transpose
transpose = a.T
print(transpose)

[[1 3]
 [2 4]]
