In [ ]:
# Array stacking means combining two or more arrays together to form a single array, either vertically or horizontally.
import numpy as np

# You can not do stacking to matrices because they are already stacked.
# You can perform stacking at vectors

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
#vertical stack
np.vstack((a,b)) #Will vertically stack two arrays
#horizontal stack
np.hstack((a,b)) #will join both 
# Column Stack 
np.column_stack((a,b)) #will stack them in columns

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
# Spilting Arrays
#You can only split 2D (eg--> matrix)not 1D(eg-->Vectors) 
c = np.arange(16).reshape(4,4)
print(c)
np.vsplit(c,2) #means split c vertically in two parts . Parts should by valid equal division
np.hsplit(c,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]