In [1]:
import numpy as np

arr = np.arange(1,31).reshape(5,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [5]:
# Indexing

arr_indexing = arr[0] #Firstly row will get targeted.
arr_indexing = arr[0,0] #we can also acess elements like this
arr_indexing=arr[4,4]
print(arr_indexing)

29


In [8]:
# Slicing
# if we want to take out the portion 

arr_slicing = arr[0:2,1:3] #in row go from 0 to 1 and in column go from 1 to 2 so u will get 2,3,8,9 in matrix form means we are slicing it out
arr_slicing= arr[2:5,3:6]
print(arr_slicing)

[[16 17 18]
 [22 23 24]
 [28 29 30]]


In [ ]:
# if you want to slice out a full column 

colm=arr[:,2] #to access full column we have to access full row so thats why we have selected whole row
print(colm)

[ 3  9 15 21 27]
