In [25]:
import numpy as np

#Columns :[Age , MathMarks , ScienceMarks]
data = np.array([
    [18,85,78], #Student1
    [19,92,88], #Student2
    [17,76,95], #Student3
    [18,65,70], #Student4
    [20,90,85]  #Student5
])

In [4]:
# Get the shape of the  matrix
data.shape

(5, 3)

In [5]:
#Find the average age of Students
np.mean(data[:,0])

np.float64(18.4)

In [7]:
# Extract math marks of all students
mathmarks=data[:,1]
print(mathmarks)

[85 92 76 65 90]


In [11]:
# Find the highest science marks
science_marks  = data[:,2].max()
# or 
science_marks = np.max(data[:,2])
print(science_marks)

95


In [ ]:
# Get details of the student who scored more than 90 in maths
marks_90 = data[:,1]
marks_90 = marks_90>90
data[marks_90] #by doing this you will get the students who scored more than 90 marks in maths.

array([[19, 92, 88]])

In [17]:
# Increase Math marks of all students by 5 .
increased_marks=data[:,1]+5
print(increased_marks)


[90 97 81 70 95]


In [20]:
# Find how many students are younger than 19
bool_age = data[:,0] < 19
len(data[bool_age])

3

In [22]:
# Calculate the average marks in each subject (column-wise mean)
np.mean(data[:,1:]) #it will give mean of whole marks of both but we want of seprate columns
# so will give axis.
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [27]:
# Get data of students who scored at least 80 in both subjects

# atleast80=(data[:,1] >=80) &  (data[:,2])
# data[atleast80]
data[(data[:,1] >=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [28]:
# Replace all Science marks < 75 with 0 
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])