In [ ]:
# Simple array making
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
a=[1,2,3.5]
# print(a) # Will print 1, 2, 3.5]
np.array(a)
#it will convert all values in float

array([1. , 2. , 3.5])

In [ ]:
a=["hello",1,2]
print(a)
np.array(a) #Convert all In Strings

['hello', 1, 2]


array(['hello', '1', '2'], dtype='<U21')

In [13]:
# Vectors -- > Single Dimensional [1,2,3,4]

l = [[1,2,3] , [4,5,6] , [7,8,9]]
print(l)

np.array(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])