In [4]:
import numpy as np

# ARANGE --> same as range excludes last value and we are doing it in array so a in front of range
# a=np.arange(1,10)
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
# Zeros --> Will give Zeroes
a = np.zeros(6) # Will give in 1D
a = np.zeros((2,4)) # Will give in 2D
print(a) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# Ones--> Will give Ones
a=np.ones(6)
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# linspace --> provides equally spreaded space between a specific range

a= np.linspace(0,10,5) #5 here means ki 5 element do 0,10 k bich mein.
print(a)

[ 0.   2.5  5.   7.5 10. ]
