In [1]:
import numpy as np

# Attributes --> We dont need to call them 

a = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a.shape # will return shape(3,3)
a.size #Will return size 9
a.dtype #Will return datatype

dtype('int64')

In [ ]:
# Methods --> we have to call Them
a.min()
a.max()
a.sum() #will give sum of all
# if we want sum of rows or column numpy provides us axis so for rows give axis = 1 for colm give axis 0
np.sum(a,axis=0) #for rows sum
np.sum(a,axis=1) #for colm sum
a.mean() #provide mean
a.std()  #provide standard deviation
a.argmax() #index of maximum value
a.argmin() #index of minimum value


np.int64(0)

In [ ]:
#Reshape and #resizing
#reshape we can convert for eg a vector into matrix
arr = np.random.randint(1,30,30)
print(arr)

[ 2  4 13  4 23 19 23  8  5 29 23 10 13 18  4  4 15 10 25 19 23  6 27  3
 11  6 19 13  2 20]


In [ ]:
arr = arr.reshape(6,5) #6*5=30 and we also have 30 elements means ki y multiply wala same rkhna jaise for 25 elements 5*5

array([[ 2,  4, 13,  4, 23],
       [19, 23,  8,  5, 29],
       [23, 10, 13, 18,  4],
       [ 4, 15, 10, 25, 19],
       [23,  6, 27,  3, 11],
       [ 6, 19, 13,  2, 20]], dtype=int32)

In [ ]:
# after doing reshape assinging it again to arr means resizing.